version: '3.8'

services:
  web:
    build: .
    container_name: sistema_fichas_app
    ports:
      - "5000:5000"
    volumes:
      - .:/projeto
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: sistema_fichas_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dados_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: sistema_fichas_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  dados_postgres:
